# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05aa39dcd375710dba65c14a2f315e0de2148d1ec69eb92826e9a1480f39a97c1d878a673c97cebe8081baa2d41a21edd16e26f7ee6ebdcb8ba2cd6af1907485

test:
  secret_key_base: a94dd434efce9e6526e5df949287fcee39bd6cb8b03086b48945103b992ae710dbc415c2651858f80736b4906f6b1478188ca3dc3a23001425d5d70e81e910da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
